image: cloud_notes_runtime:latest

stages:
  - test
  - deploy_frontend

variables:
  GLEAM_ENV: dev
  VITE_BASE_PATH: "/cloud-notes/"

cache:
  key: gleam
  paths:
    - build/
    - ~/.cache/rebar3
    - ~/.cache/gleam

test:
  stage: test
  script:
    - cd server
    - gleam deps download
    - gleam test

pages:
  stage: deploy_frontend
  script:
    - cd client
    - bun install
    - bun vite build
    - mv dist ../public
  artifacts:
    paths:
      - public
